apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frolf-bot-backend
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://frolf-bot.duckdns.org"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
spec:
  rules:
    - host: frolf-bot.duckdns.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: frolf-bot-backend
                port:
                  number: 8080
  tls:
    - hosts:
        - frolf-bot.duckdns.org
      secretName: frolf-bot-pwa-tls
