apiVersion: apps/v1
kind: Deployment
metadata:
  name: frolf-bot-pwa
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frolf-bot-pwa
  template:
    metadata:
      labels:
        app: frolf-bot-pwa
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: frolf-bot-pwa
          image: us-ashburn-1.ocir.io/id2uwn5pyixh/frolf-bot-pwa@sha256:415db8c5a8c9a6780db43b88d43f8b523f254edf880089fe7869ba8007df8eea
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: BODY_SIZE_LIMIT
              value: "Infinity"
            - name: PRIVATE_API_URL
              value: "http://frolf-bot-backend.frolf-bot.svc.cluster.local"
            - name: PUBLIC_NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: frolf-pwa-config
                  key: PUBLIC_NATS_URL
            - name: PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frolf-pwa-config
                  key: PUBLIC_API_URL
            - name: PUBLIC_OTEL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: frolf-pwa-config
                  key: PUBLIC_OTEL_ENDPOINT
            - name: PUBLIC_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: frolf-pwa-config
                  key: PUBLIC_DEBUG
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
