apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-frontend
  namespace: resume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-frontend
  template:
    metadata:
      labels:
        app: resume-frontend
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: resume-frontend
          image: resume-frontend
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
