apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
  - argocd-image-updater.yaml
  - argocd-image-updater-crds.yaml
  - cert-manager.yaml
  - cert-manager-issuers.yaml
  - namespace-manager.yaml
  - oci-csi-driver.yaml
  - nginx-ingress-app.yaml
  - mimir-app.yaml
  - loki-app.yaml
  - tempo-app.yaml
  - alloy-app.yaml
