apiVersion: v1
kind: Service
metadata:
  name: resume-backend-svc
  labels:
    job: go-api
    app: resume-backend
spec:
  selector:
    app: resume-backend
  ports:
    - name: api-port
      protocol: TCP
      port: 8000
      targetPort: 8000
