apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: resume-backend
    newName: us-ashburn-1.ocir.io/id2uwn5pyixh/resume/backend
    newTag: latest
  - name: us-ashburn-1.ocir.io/id2uwn5pyixh/resume/backend
    newTag: latest
