apiVersion: v1
kind: Service
metadata:
  name: resume-frontend-svc
  namespace: resume-app
  labels:
    job: astro-web
    app: resume-frontend
    tier: frontend
spec:
  selector:
    app: resume-frontend
  ports:
    - name: web-port
      port: 443
      targetPort: 3000
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
