apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: resume-frontend
    newName: us-ashburn-1.ocir.io/id2uwn5pyixh/resume/frontend
    newTag: e81cd1c
  - name: us-ashburn-1.ocir.io/id2uwn5pyixh/resume/frontend
    newTag: 386c664
