apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: resume-frontend
    newName: us-ashburn-1.ocir.io/id2uwn5pyixh/resume/frontend
    digest: sha256:675a7fc70591176e0960ec55009ec7f8b0d531f8a69ddbc901a93e3c6fb8d4d7
  - name: us-ashburn-1.ocir.io/id2uwn5pyixh/resume/frontend
    digest: sha256:6faeeb872e05b25c064b8b8dd846bf5458999a2d13314e54c4b58243fb02936c
