apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform/00-argocd.yaml
  - platform/00-platform-cert-manager.yaml
  - platform/01-argocd-image-updater-crds.yaml
  - platform/01-platform-cluster-resources.yaml
  - platform/02-argocd-image-updater.yaml
  - platform/oci-csi-driver.yaml
  - platform/platform-shared-services-appset.yaml
  - platform/sealed-secrets-manifests.yaml
  - applicationsets
  - apps
  - image-updaters
