apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps/resume-backend.yaml
  - apps/resume-frontend.yaml
  - apps/frolf-backend.yaml
  - apps/frolf-discord.yaml
  - apps/frolf-postgres.yaml
  - apps/frolf-nats.yaml
  - apps/resume-postgres.yaml
