apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - discord-deployment.yaml

images:
  - name: frolf-bot-discord
    newName: us-ashburn-1.ocir.io/id2uwn5pyixh/frolf-bot/discord
    newTag: latest
labels:
  - includeSelectors: true
    pairs:
      app: frolf-bot-discord
      managed-by: lich-king
