apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - discord-deployment.yaml

images:
  - name: frolf-bot-discord
    newName: us-ashburn-1.ocir.io/id2uwn5pyixh/frolf-bot/discord
    digest: sha256:faa4446c1291cb5ff9db85ef72f74509d17af6f4efb0494693460a34944052fb
labels:
  - includeSelectors: true
    pairs:
      app: frolf-bot-discord
      managed-by: lich-king
