apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Platform apps
  - platform/

  # Observability apps
  - observability/

  # User apps
  - apps/

  # Image Updater custom resources
  - image-updaters/

  # ArgoCD Projects
  - projects/

  # Cluster resources
  - cluster-resources/
