# Kubernetes version
kube_version: "v1.31.4"

# Network plugin
kube_network_plugin: flannel

# Enable Helm
helm_enabled: true

# Disable stuff you don't need
dashboard_enabled: false
metrics_server_enabled: true

container_manager: containerd

# Download settings
download_run_once: true
download_localhost: false

# Enable ping check for access_ip
ping_access_ip: true
