apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-app.yaml
  - loki-app.yaml
  - mimir-app.yaml
  - tempo-app.yaml
  - alloy-app.yaml
  - kube-state-metrics-app.yaml
  - node-exporter-app.yaml
