apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resume-app-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: apps
  source:
    repoURL: https://github.com/Black-And-White-Club/all-infrastructure
    targetRevision: main
    path: kustomize/resume-app/base
  destination:
    server: https://kubernetes.default.svc
    namespace: resume-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
