apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # The Application Definitions
  - sealed-secrets-manifests.yaml

  # The Projects
  - platform-project.yaml
  - resume-project.yaml
  - frolf-bot-project.yaml
  - observability-project.yaml

  # Platform Resources
  - 00-argocd.yaml
  - 00-platform-cert-manager.yaml
  - 01-argocd-image-updater-crds.yaml
  - 01-platform-cluster-resources.yaml
  - 02-argocd-image-updater.yaml
  - oci-csi-driver.yaml

  # Any other files in this directory that should be applied
