apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-argocd.yaml
  - 00-platform-cert-manager.yaml
  - 01-argocd-image-updater-crds.yaml
  - 01-platform-cluster-resources.yaml
  - 02-argocd-image-updater.yaml
  - platform-project.yaml
  - frolf-bot-project.yaml
  - observability-project.yaml
  - resume-project.yaml
  - oci-csi-driver.yaml
  - platform-shared-services-appset.yaml
  - sealed-secrets-manifests.yaml
