apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Resume App
  - resume-backend.yaml
  - resume-frontend.yaml
  - resume-postgres.yaml

  # Frolf App
  - frolf-backend.yaml
  - frolf-discord.yaml
  - frolf-nats.yaml
  - frolf-postgres.yaml
