apiVersion: v1
kind: Service
metadata:
  name: resume-backend-postgresql
  namespace: resume-db
spec:
  selector:
    app: resume-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None
